version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: oauth2_db
    environment:
      - POSTGRES_DB=oauth2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "127.0.0.1:5432:5432"
